config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'message', to: 'messages#create'
  resources :users

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_last_few, -> {order(created_at: :desc).limit(17)}
end

app/models/user.rb
class User < ApplicationRecord

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 20 }
  has_many :messages

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?, :require_login

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  before_action :require_login
  def index

    @message = Message.new
    @messages = Message.custom_last_few

  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :require_login
  def create

    message = current_user.messages.build(message_param)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel', modify_message: message_render(message)
      redirect_to root_path
    end
  end

  private
  def message_param
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :define_logged_in_redirect, only: [:new, :create]
  def new


  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login successful!"
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = 'Login failed!'
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logout successful!"
    redirect_to login_path
  end


  private

  def define_logged_in_redirect
    if logged_in?
      flash[:alert] = "You are already logged in!"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end

  def new

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular users icon purple"></i>
  Say something
</h4>

<div class="ui two column grid">
  <!-- left side card starts-->
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages%>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, HTML: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%=f.text_field :body%>
              <%=f.button '<i class="bordered inverted purple edit icon"></i>'.html_safe%>
            </div>
          </div>
        <%end %>
      </div>
    </div>
  </div>
  <!-- left side card ends-->
  <!-- right side card starts-->
  <div class="four wide column">

    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>

  </div>
  <!-- right side card ends-->
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>

  <div class="ui <%=message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%=message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <div class="ui small inverted menu">
    <div class ="ui container">
      <%=link_to 'Chat room', root_path, class: 'item' %>
      <a class="item">
        Messages
      </a>
      <div class="right menu">
        <div class="ui dropdown item">
          Account <i class="dropdown icon"></i>
          <div class="menu">
            <% if logged_in? %>
              <%=link_to 'Logout', logout_path, class: 'item', method: :delete%>
            <%end %>
            <% if !logged_in? %>
              <%=link_to 'Login', login_path, class: 'item' %>
              <%=link_to 'Signup', signup_path, class: 'item' %>
            <%end %>
          </div>
        </div>
        <div class="item">
          <div class="ui primary button">Sign Up</div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <div class="ui container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%=message.user.username %></em> : <%=message.body %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<br><br>
New user

app/views/users/show.html.erb
<br><br>Login done. <%=@user.username %>